config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'devise/sessions'
   }

  root 'items#index'
  resources :items do 
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
    member do
      get 'confirm'
      post 'pay'
    end
    resources :comments, only: [:create, :destroy]
  end 
  resources :users, only: :show
  resources :addresses, only:[:new, :create, :edit, :update]
  resources :cards, only: [:new, :create, :edit, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fav_items, through: :favorites, source: :item
  has_one :card
  has_one :address
  has_many :bought_items, foreign_key: 'buyer_id', class_name: 'Item'
  has_many :saling_items, ->{where("buyer_id is NULL")},foreign_key: 'saler_id', class_name: 'Item'
  has_many :sold_items, ->{where("buyer_id is not NULL")},foreign_key: 'saler_id', class_name: 'Item'
  has_many :comments,  dependent: :destroy

  validates :nickname, :last_name, :first_name, :last_name_furigana, :first_name_furigana, :birthday, presence: true
  validates :last_name, :first_name, format: { with: /\A[ぁ-んァ-ヶー一-龠]+\z/}
  validates :last_name_furigana, :first_name_furigana, format: { with: /\A[あ-ん゛゜ぁ-ぉゃ-ょー]+\z/}
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_secure_password
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def new
    @user =User.new
  end
  
  def create
    @user =User.new(user_params)
    if @user.save
      bypass_sign_in(@user)
      redirect_to new_address_path, notice: "ユーザー「#{@user.nickname}」を登録しました。"
    else
      render 'new'
    end
  end

 
  private 
  def user_params
    params.require(:user).permit(:nickname,:email,:password, :first_name,:last_name,:first_name_furigana,:last_name_furigana,:birthday)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new
  end

  def destroy
    redirect_to root_path
  end
  # def create
  #   user =User.find_by(email: session_params[:email])

  #   if user&.authenticate(session_params[:password])
  #     session[:user_id] = user.id
  #     redirect_to root_path, notice: 'ログインしました。'
  #   else
  #     render :new
  #   end
  # end

  # private
  # def session_params
  #   params.permit(:email, :password)
  # end

 end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # @user = User.find(params[:id])
    @user= current_user
    @address= current_user.address
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
          .field
          .field-label
            = f.label :password
            %i (英数字8文字以上)
          .field-input
            = f.password_field :password, autocomplete: "off"
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off"
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.mypage
  %h2.mypage__header= "マイページ"
  .mypage__content
    %h3.upper 商品
    %ul.mypage-lists 
      %li.mypage-list
        =link_to '購入リスト', '#', class: 'mypage-list__item bought-item'
      %li.mypage-list
        =link_to '出品リスト', '#', class: 'mypage-list__item sailing-item'
      %li.mypage-list
        =link_to 'お気に入り商品', '#', class: 'mypage-list__item fav-item'
    %h3.middle 設定
    %ul.mypage-lists 
      - if current_user.address.present?
        %li.mypage-list
          =link_to '発送元・お届け先住所変更', edit_address_path(@address), class: 'mypage-list__item shipping'
      - else
        %li.mypage-list
          =link_to '発送元・お届け先住所変更', new_address_path, class: 'mypage-list__item shipping'
      %li.mypage-list
        =link_to 'メールアドレス変更', '#', class: 'mypage-list__item email'
      %li.mypage-list
        =link_to 'パスワード変更', '#', class: 'mypage-list__item password'
      %li.mypage-list
        =link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'mypage-list__item logout'
    %h3.lower お支払い
    %ul.mypage-lists
      - if current_user.card.present?
        %li.mypage-list
          =link_to 'クレジットカード登録・変更', edit_card_path(current_user.card), class: 'mypage-list__item card'
      -else
        %li.mypage-list
          =link_to 'クレジットカード登録・変更', new_card_path, class: 'mypage-list__item card'