config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'devise/sessions'
   }

  root 'items#index'
  resources :items do 
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
    member do
      get 'confirm'
      post 'pay'
    end
    resources :comments, only: [:create, :destroy]
  end 
  resources :users, only: :show
  resources :addresses, only:[:new, :create, :edit, :update]
  resources :cards, only: [:new, :create, :edit, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :saler, class_name: 'User', optional: true
  belongs_to :buyer, class_name: 'User', optional: true
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :category, optional: true
  belongs_to :brand, optional: true
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  has_many :comments, dependent: :destroy

  validates_associated :item_images
  validates :price, numericality: {greater_than_or_equal_to: 300,less_than_or_equal_to: 9999999}

  with_options presence: true do
    validates :name
    validates :discription
    validates :price
    validates :condition
    validates :postage
    validates :prefecture
    validates :shipping_date
    validates :category_id
    validates :item_images
  end



  enum condition: { 新品・未使用: 0, 未使用に近い: 1, 目立った傷や汚れなし: 2, やや傷や汚れあり: 3, 傷や汚れあり: 4, 全体的に状態が悪い: 5 }

  enum postage:{ 送料込み（出品者負担）: 0, 着払い（購入者負担）: 1}

  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,
  }

  enum shipping_date:{ １〜２日で発送: 0, ２〜３日で発送: 1, ４〜７日で発送: 2}

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'payjp'

  before_action :set_params, only: [:show, :destroy, :edit, :update, :confirm, :pay, :correct_user]
  before_action :move_to_index,  except: [:index, :show]
  before_action :move_to_index2,  only: :confirm
  before_action :move_to_index3,  only: :show
  before_action :correct_user, only: [:edit, :update]
  before_action :set_card, only: [:confirm, :pay]
  before_action :payjp_api_key, only: [:confirm, :pay]
  
  def index
    @items = Item.includes(:saler)

    @images = [] 
    @items.each do |item|
      @images << item.item_images.first    

    end
  end

  def new
    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    @item = Item.new
    @item.item_images.new
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  def show
    @category= @item.category
    @images= @item.item_images
    @first_image= @images.first
    @other_images= @images.where.not(id: @images.select('min(id)'))
    @comment = Comment.new
    @comments = @item.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = ['選択してください']
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end

  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to edit_item_path(@item)
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else 
      render item_path(@item)
    end
  end

  def confirm
    @image= @item.item_images.first
    @address= current_user.address
    if @card.present?
      customer= Payjp::Customer.retrieve(@card.customer_id)
      @card= customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    if @card.present?
      @item.update(buyer_id: current_user.id)

      charge= Payjp::Charge.create(
        amount: @item.price,
        customer: @card.customer_id,
        currency: 'jpy',
      )
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :discription, :condition, :postage, :prefecture, :shipping_date, :price, :category_id, :brand_id, :buyer_id, item_images_attributes: [ :image, :_destroy, :id]).merge(saler_id: current_user.id)
  end

  def set_params
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def move_to_index2
    @item= Item.find(params[:id])
    redirect_to action: :index if current_user.id == @item.saler.id
  end

  def move_to_index3
    @item= Item.find(params[:id])
    redirect_to action: :index if @item.buyer_id.present?
  end

  def correct_user
    if current_user.id !=  @item.saler_id
      redirect_to root_path
    end
  end

  def set_card
    @card= current_user.card
  end

  def payjp_api_key
    Payjp.api_key= Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_buy-confirmation.html.haml
%body
  .confirmation-container
    .confirmation-container__header
      %h1.header-logo
        = link_to image_tag("http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg"), root_path

  =form_for root_path do |form| 
    .confirmation-main
      .confirmation-main__container
        %h2.header-title 購入内容の確認
        
        %section.item-content
          .item-content-inner
            .item-content-inner__box
              %h3.item-content__inner__box__image
                =link_to image_tag("macbook-air-space-gray-config-201810.jpeg",size: '80x50'), "#"
              .item-content-inner__box__detail
                %p.item-content__inner__box__detail__name 13インチMacBook Air - スペースグレイ Apple MWTJ2J/A
                %p.item-content__inner__box__detail__price
                  %span.price ¥115,280
                  %span.item-shipping-fee （税込）送料込み

        %section.item-content2
          .item-content2__inner
            .item-content2__inner__form
            %ul.item-content2-price
              %li.item-content2-price-content
                .item-content2-price-textbox 支払金額
                .item-content2-price-price-amount
                  %span.amount-price ¥115,280
                   
            %ul.item-content2-point-exercise
              %li.item-content2-point-exercise-content
          
                .item-content2-point-inner
                  =form.check_box :checkbox,id: :point    
                  %i.icon-check
                  %label ポイントを使用（所持ポイント:P0）
            %section.payment-info
              .payment-info-inner
                .content
                  %h3.left-content 支払い方法                
                  =link_to "変更する", "#",class:"right-content"
                  
                %p.payment-card-info
                  クレジットカード
                  %br/
                  ************6883
                  %br/
                  有効期限 06 / 21

                %figure.credit-card-logo
                  =link_to image_tag("//pcweb-assets.mercdn.net/assets/img/card/visa.svg?2246739708", size: "49x15")

            %section.delivery-info
              .delivery-info__inner
                %h4.delivery-info-content 配送先
                =link_to "登録してください", "#" 
                %i.icon-plus-circle
                  

            %section.purchase-button
              =form.submit "購入する",class:"btn-submit"

  .confirmation-footer
    .confirmation-footer__content
      %ul.menu
        %li プライバシーポリシー
        %li FURIMA利用規約
        %li 特定商取引に関する表記

      .confirmation-footer__content__nav-company-logo
        =link_to image_tag("http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg",size: '80x65') 

      %p
        %small © FURIMA
        %script{src: "//pcweb-assets.mercdn.net/assets/js/app.js?3178455151"}

app/views/items/_footer.html.haml
.furima-main__lower-image
  .furima-main__lower-image__content
    %h2.furima-main__lower-image__content__title だれでもかんたん、人生を変えるフリマアプリ
    %p.furima-main__lower-image__content__text 今すぐ無料ダウンロード！
  .furima-main__lower-image__content__icon
    = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",  alt: "appstore", width: "180px"), root_path, class:"furima-main__lower-image__content__icon__abtn"
    = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", alt:"googleplay", width: "180px"), root_path, class:"furima-main__lower-image__content__icon__abtn"
.furima-footer
  %ul.furima-footer__content
    %li.furima-footer__content__list
      %h2.furima-footer__content__list__top FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", root_path
        %li
          = link_to "プライバシーポリシー", root_path
        %li
          = link_to "FURIMA利用規約", root_path
        %li
          = link_to "ポイントに関する特約", root_path
    %li.furima-footer__content__list
      %h2.furima-footer__content__list__top FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", root_path
        %li
          = link_to "ブランド一覧", root_path
    %li.furima-footer__content__list
      %h2.furima-footer__content__list__top ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", root_path
        %li
          = link_to "FURIMAロゴ利用ガイドライン", root_path
        %li
          = link_to "お知らせ", root_path
  = link_to image_tag("logo-white.png", class:"furima-footer__logo"), root_path
  %p.furima-footer__p © FURIMA
-# -if user_signed_in?
-#   = link_to new_item_path do
-#     .sell-btn
-#       %p.sell-btn__text 出品する
-#       = image_tag("icon_camera.png", width: "60%")
-# - else
-#   = link_to new_user_registration_path do
-#     .sell-btn
-#       %p.sell-btn__text 出品する
-#       = image_tag("icon_camera.png", width: "60%")

app/views/items/_header.html.haml
.furima-header
  .furima-header__content
    = form_for root_path do |f|
      .furima-header__content__main
        = link_to image_tag("logo.png", class: "furima-header__content__main__logo"), root_path
        .furima-header__content__main__search    
          = f.text_field :name, placeholder: "キーワードから探す", class: "furima-header__content__main__search__input"
          = image_submit_tag ("icon-search1.png"), class: "furima-header__content__main__search__icon", value: ""
      .furima-header__content__main__btn
        .furima-header__content__main__btn__left
          %ul
            %li           
              =link_to "#", class:"category__search search__btn" do
                %i.fas.fa-bars.category__icon カテゴリー   
                %i.fas.fa-bars.brand__icon ブランド  

              %ul.category__parent.category__list
                - set_parents.each do |parent|
                  %li
                    =link_to "#", class: "category__parent--name" do
                      = parent.name
                    %ul.category__child.category__list
                      - parent.children.each do |child|
                        %li
                          = link_to "#", class: "category__child--name" do
                            = child.name
                          %ul.category__grandchild.category__list
                            - child.children.each do |grandchild|
                              %li
                                = link_to "#", class: "category__child--name" do  
                                  = grandchild.name 


          
        .furima-header__content__main__btn__right
          - if user_signed_in?
            = link_to "マイページ", user_path(current_user.id)
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          - else
            = link_to "ログイン", new_user_session_path, class:"furima-header__content__main__btn__right__login"
            = link_to "新規会員登録", new_user_registration_path, class:"furima-header__content__main__btn__right__signup"

app/views/items/_lower-image.html.haml
.furima-main__lower-image
    .furima-main__lower-image__content
      %h2.furima-main__lower-image__content__title だれでもかんたん、人生を変えるフリマアプリ
      %p.furima-main__lower-image__content__text 今すぐ無料ダウンロード！
      .furima-main__lower-image__content__icon
        = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",  alt: "appstore", width: "180px"),"root_path", class:"furima-main__lower-image__content__icon__abtn"
        = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", alt:"googleplay", width: "180px"),"root_path", class:"furima-main__lower-image__content__icon__abtn"

app/views/items/confirm.html.haml
%body
  .confirmation-container
    .confirmation-container__header
      %h1.header-logo
        = link_to image_tag("http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg"), "root_path"


  .confirmation-main
    .confirmation-main__container
      %h2.header-title 購入内容の確認
      
      %section.item-content
        .item-content-inner
          .item-content-inner__box
            %h3.item-content__inner__box__image
              =image_tag @image.image_url, size: '80x80'
            .item-content-inner__box__detail
              %p.item-content__inner__box__detail__name 
                = "#{@item.name}"
              %p.item-content__inner__box__detail__price
                %span.price 
                  = "¥#{@item.price}"
                %span.item-shipping-fee （税込）送料込み

      %section.item-content2
        .item-content2__inner
          .item-content2__inner__form
          %ul.item-content2-price
            %li.item-content2-price-content
              .item-content2-price-textbox 支払金額
              .item-content2-price-price-amount
                %span.amount-price 
                  = "¥#{@item.price}"
                  
          %ul.item-content2-point-exercise
            %li.item-content2-point-exercise-content
          %section.payment-info
            .payment-info-inner
              .content
                %h3.left-content 支払い方法 
                - if current_user.card.present?
                  = link_to '変更する', new_card_path, class: 'update_card'
                  %p.payment-card-info
                    クレジットカード
                    %br/
                    = "************#{@card.last4}"
                    %br/
                    -if @card.exp_month < 10
                      = "有効期限 0#{@card.exp_month} / #{@card.exp_year}"
                    -else
                      = "有効期限 #{@card.exp_month} / #{@card.exp_year}"
                  %figure.credit-card-logo
                    -case @card.brand
                    -when "Visa"
                      =image_tag("//pcweb-assets.mercdn.net/assets/img/card/visa.svg?2246739708", size: "49x15")
                    -when "MasterCard"
                      =image_tag("//pcweb-assets.mercdn.net/assets/img/card/master-card.svg?2226206775", size: "49x15")
                    -when "JCB"
                      =image_tag("//pcweb-assets.mercdn.net/assets/img/card/jcb.svg?2226206775", size: "49x15")
                    -when "American Express"
                      =image_tag("//pcweb-assets.mercdn.net/assets/img/card/american_express.svg?2226206775", size: "49x15")
                    -when "Diners Club"
                      =image_tag("//pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?2226206775", size: "49x15")
                    -when "Discover"
                      =image_tag("//pcweb-assets.mercdn.net/assets/img/card/discover.svg?2226206775", size: "49x15")
                - else 
                  = link_to '登録してください', new_card_path, class: 'card_resistration'

          %section.delivery-info
            .delivery-info__inner
              %h4.delivery-info-title 配送先
              -if current_user.address.present?
                %p.delivery-info-content
                  ="〒#{@address.postal_code}"
                  %br/
                  ="#{@address.prefecture_name} #{@address.city} #{@address.street}"
                  %br/
                  ="#{@address.last_name} #{@address.first_name}"
              -else
                =link_to "登録してください", "#", class: 'address_resistration' 
                

          %section.purchase-button
            -if @card.present? && current_user.address.present?
              =button_to "購入する", pay_item_path, data: {confirm: '購入を確定しますか？'}, class: 'purchase-button__not-disabled'
            - else
              =button_to "購入する", pay_item_path, disabled: true, class: 'purchase-button__disabled'

.confirmation-footer
  .confirmation-footer__content
    %ul.menu
      %li プライバシーポリシー
      %li FURIMA利用規約
      %li 特定商取引に関する表記

    .confirmation-footer__content__nav-company-logo
      =image_tag("http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg",size: '80x65') 

    %p
      %small © FURIMA
      %script{src: "//pcweb-assets.mercdn.net/assets/js/app.js?3178455151"}

app/views/items/index.html.haml
.furima-main
  .furima-main__top-image
    .furima-main__top-image__content
      %h2.furima-main__top-image__content__title 
        %br 人生を変えるフリマアプリ
      %p.furima-main__top-image__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br フリマアプリです
        .furima-main__top-image__content__btn
          = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", alt: "appstore", width: "180px"), root_path
          = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", alt:"googleplay", width: "180px"), root_path
  .furima-main__upper-info
    %h2.furima-main__upper-info__title FURIMAが選ばれる3つの理由
    %ul.furima-main__upper-info__lists
      %li.furima-main__upper-info__lists__list
        .furima-main__upper-info__lists__list__img
          %span.furima-main__upper-info__lists__list__img__num 1
          = image_tag "pict-reason-01.jpg", width: "300px"
        %h2.furima-main__upper-info__lists__list__text
          %span 3分
          ですぐに出品
        %p.furima-main__upper-info__lists__list__text2 スマホで入力するだけで簡単に出品できる！
      %li.furima-main__upper-info__lists__list
        .furima-main__upper-info__lists__list__img
          %span.furima-main__upper-info__lists__list__img__num 2
          = image_tag "pict-reason-02.jpg", width: "300px"
        %h2.furima-main__upper-info__lists__list__text
          %span シンプル
          で使いやすい
        %p.furima-main__upper-info__lists__list__text2 めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.furima-main__upper-info__lists__list
        .furima-main__upper-info__lists__list__img
          %span.furima-main__upper-info__lists__list__img__num 3
          = image_tag "pict-reason-03.jpg", width: "300px"
        %h2.furima-main__upper-info__lists__list__text
          手数料
          %span 業界最安
        %p.furima-main__upper-info__lists__list__text2 最大3%でお得に出品&購入！
  .furima-main__middle-image
    .furima-main__middle-image__content
      %h2.furima-main__middle-image__content__title 会員数日本一位
      %p.furima-main__middle-image__content__text
        FURIMAは、フリマアプリで最も人気。
        %br
          出品・購入回数も業界最多です！
          %br
            ほしかったあの商品に出会えるかもしれません。
      .furima-main__middle-image__content__btn
        = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", alt: "appstore", width: "180px"), root_path
        = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",  alt:"googleplay", width: "180px"), root_path
  .furima-main__lower-info
    %h2.furima-main__lower-info__title FURIMAの特徴
    %ul.furima-main__lower-info__lists
      %li.furima-main__lower-info__lists__list
        = image_tag "icon-01.png", class:"furima-main__lower-info__lists__list__img"
        %h3.furima-main__lower-info__lists__list__title 簡単に売り買いできる
        %p.furima-main__lower-info__lists__list__text スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.furima-main__lower-info__lists__list
        = image_tag "icon-03.png", class:"furima-main__lower-info__lists__list__img"
        %h3.furima-main__lower-info__lists__list__title 売上金は即日振込みに対応
        %p.furima-main__lower-info__lists__list__text 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.furima-main__lower-info__lists__list
        = image_tag "icon-04.png", class:"furima-main__lower-info__lists__list__img"
        %h3.furima-main__lower-info__lists__list__title 様々な支払いに対応
        %p.furima-main__lower-info__lists__list__text お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .furima-main__pickup
    %h2.furima-main__pickup__category ピックアップアイテム
    .furima-main__pickup__content
      %h3.furima-main__pickup__content__link__title 新規投稿商品
    .furima-main__pickup__content__lists
      - @items.zip(@images).each do |item,image|
        .furima-main__pickup__content__lists__list
          = link_to item_path(item), class:"furima-main__pickup__content__lists__list__link" do
            .furima-main__pickup__content__lists__list__link__img
              = image_tag image.image_url, size: "220x210"
              - if item.buyer_id.present?
                .items-box_photo__sold
                  .items-box_photo__sold__inner 
                    SOLD
              
            .furima-main__pickup__content__lists__list__link__box
              %h3.furima-main__pickup__content__lists__list__link__box__name 
                = item.name
              .furima-main__pickup__content__lists__list__link__box__price
                %ul
                  %li 
                    = item.price 
                    円 (税込)
-if user_signed_in?
  = link_to new_item_path do
    .sell-btn
      %p.sell-btn__text 出品する
      = image_tag("icon_camera.png", width: "60%")
- else
  = link_to new_user_registration_path do
    .sell-btn
      %p.sell-btn__text 出品する
      = image_tag("icon_camera.png", width: "60%")
 

app/views/items/pay.html.haml
購入完了
=link_to "戻る", root_path

app/views/items/show.html.haml
.narrow-downitem
  %ul.narrow-downitem__category
    %li.narrow-downitem__category__list
      = link_to "FURIMA" ,root_path 
    %li.narrow-downitem__category__list
      %i.fa.fa-angle-right.icon
    %li.narrow-downitem__category__list
      = link_to "#{@category.root.name}" ,root_path 
    %li.narrow-downitem__category__list
      %i.fa.fa-angle-right 
    %li.narrow-downitem__category__list
      = link_to "#{@category.parent.name}" ,root_path
    %li.narrow-downitem__category__list
      %i.fa.fa-angle-right
    %li.narrow-downitem__category__list
      = link_to "#{@category.name}" ,root_path  
    %li.narrow-downitem__category__list
      %i.fa.fa-angle-right
    %li.narrow-downitem__category__list
      = link_to "#{@item.name}" ,item_path(@item)

.item-main
  .item-main__show-item
    .item-main__show-item__main-content
      .item-main__show-item__main-content__content
        .item-main__show-item__main-content__content__item
          %h.item-main__show-item__main-content__content__item__name
            = "#{@item.name}"
          .item-main__show-item__main-content__content__item__image
            %ul.item-main__show-item__main-content__content__item__image__details
              %li.item-main__show-item__main-content__content__item__image__details__pictures
                = image_tag @first_image.image_url, class: 'item-main__show-item__main-content__content__item__image__details__pictures__image',size: "330x330"
                %ul.item-main__show-item__main-content__content__item__image__details__pictures__sub-pictures
                  -@other_images.each do |image|
                    %li.item-main__show-item__main-content__content__item__image__details__pictures__sub-pictures__list1
                      = image_tag image.image_url, class: 'item-main__show-item__main-content__content__item__image__details__pictures__sub-pictures__list1__image',size:"140x87"
          .item-main__show-item__main-content__content__item__price
            %span
              ="¥#{@item.price}"
            .item-main__show-item__main-content__content__item__price__other
              %span (税込)
              -if @item.postage == "送料込み（出品者負担）"
                %span 送料込み
              -else
                %span 着払い
          .item-main__show-item__main-content__content__item__text 
            = "#{@item.discription}"
          - if user_signed_in? && current_user.id == @item.saler_id
            =link_to '商品の編集', edit_item_path(@item), class: 'edit_item-btn'
            %span.or or
            =link_to 'この商品を削除する', item_path(@item), method: :delete, class: 'destroy_item-btn'
          - elsif user_signed_in?
            =link_to '購入画面に進む', confirm_item_path(@item), class: 'confirm_item-btn'
          .item-main__show-item__main-content__content__item__main-table
            %table
              %tbody
                %tr.test1
                  %th 出品者
                  %td 
                    = "#{@item.saler.nickname}"
                %tr.test2
                  %th カテゴリー
                  %td
                    = link_to "#{@category.root.name}","root_path", class:"category1"             
                    = link_to "#{@category.parent.name}","root_path", class:"category2"             
                    = link_to "#{@category.name}","root_path", class:"category3"
            
                %tr.test3
                  %th ブランド
                  %td
                    -# ="#{@item.brand.name}"
                %tr.test4
                  %th 商品サイズ
                  %td
                %tr.test5
                  %th 商品の状態
                  %td
                    ="#{@item.condition}"
                %tr.test6
                  %th 配送料の負担
                  %td
                    ="#{@item.postage}"
                %tr.test7
                  %th 発送元の地域
                  %td
                    ="#{@item.prefecture}"
                %tr.test8
                  %th 発送日の目安
                  %td
                    ="#{@item.shipping_date}"

              
          .item-main__show-item__main-content__content__item__option
            %ul
              %li.likeBtn
                %i.fa.fa-star.icon
                = link_to 'お気に入り 0', '#'
            
        .item-main__show-item__main-content__content__comment
          %ul.comments
          = form_with(model: [@item, @comment], id: "new_comment") do |f|
            =f.text_area :content, {class: "textarea"}
            %p.notice
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            .comment-button1                
              = f.submit "コメントする",{class: 'comment-button'}
              %i.fa.fa-comment.icon-comment
              
            
            %h4.comment コメント一覧
            .comment-box
              - @comments.each do |comment|
                -# .comment_user_content
                -#   = comment.user.nickname
                -#   = comment.content
                .comment_user_content
                  .profile
                    .profile__name
                      =comment.user.nickname
                    .profile__right
                      .image
                        %i.fas.fa-user-circle
                      .seller_or_buyer
                        出品者
                  .comment
                    .comment__text
                      =comment.content
                    .comment__bottom
                      .comment__trash
                        %a{"data-method" => "delete", :href => "/items/${comment.item_id}/comments/${comment.comment_id}", :item_id => "@item", :rel => "nofollow"}
                          %i.fa.fa-trash


        %ul.item-main__show-item__main-content__content__link
          %li.left
            %i.fa.fa-angle-left.icon
            = link_to "前の商品" ,root_path 
          %li.right
            = link_to "後ろの商品" ,root_path 
            %i.fa.fa-angle-right.icon
        .item-main__show-item__main-content__more-item
          = link_to "#{@category.root.name}をもっと見る" ,root_path