config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'devise/sessions'
   }

  root 'items#index'
  resources :items do 
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
    member do
      get 'confirm'
      post 'pay'
    end
    resources :comments, only: [:create, :destroy]
  end 
  resources :users, only: :show
  resources :addresses, only:[:new, :create, :edit, :update]
  resources :cards, only: [:new, :create, :edit, :destroy]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  MONTHS = [
    "01","02","03","04","05","06","07","08","09","10","11","12"
    ]
  
    YEARS = [
      "2020","2021","2022","2023","2024","2025","2026","2027","2028","2029","2030","2031","2032","2033","2034","2035"
    ]
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'
  before_action :payjp_api_key, only: [:create, :edit, :destroy]

  def new
  end

  def create

    customer= Payjp::Customer.create(
      card: params['payjpToken'],
      metadata: {user_id: current_user.id}
    )

    @card= Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
    if @card.save
      redirect_to edit_card_path(@card)
    else
      render :new
    end
  end

  def edit
    @card= current_user.card
    customer= Payjp::Customer.retrieve(@card.customer_id)
    @card = customer.cards.retrieve(@card.card_id)
  end

  def destroy
    @card= current_user.card
    customer= Payjp::Customer.retrieve(@card.customer_id)
    if @card.destroy
      customer.delete
    end
  end

  private

  def payjp_api_key
    Payjp.api_key= Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/create.html.haml
完了
=link_to "戻る", root_path

app/views/cards/destroy.html.haml
カードを削除しました
=link_to "新しいカードを登録する", new_card_path

app/views/cards/edit.html.haml
%section.payment-info
  .payment-info-inner
    - if current_user.card.present?
      .content
        %h3.left-content クレジットカード一覧
        %p.payment-card-info
          %br/
          = "************#{@card.last4}"
          %br/
          -if @card.exp_month < 10
            = "有効期限 0#{@card.exp_month} / #{@card.exp_year}"
          -else
            = "有効期限 #{@card.exp_month} / #{@card.exp_year}"
        %figure.credit-card-logo
          -case @card.brand
          -when "Visa"
            =image_tag("//pcweb-assets.mercdn.net/assets/img/card/visa.svg?2246739708", size: "49x15")
          -when "MasterCard"
            =image_tag("//pcweb-assets.mercdn.net/assets/img/card/master-card.svg?2226206775", size: "49x15")
          -when "JCB"
            =image_tag("//pcweb-assets.mercdn.net/assets/img/card/jcb.svg?2226206775", size: "49x15")
          -when "American Express"
            =image_tag("//pcweb-assets.mercdn.net/assets/img/card/american_express.svg?2226206775", size: "49x15")
          -when "Diners Club"
            =image_tag("//pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?2226206775", size: "49x15")
          -when "Discover"
            =image_tag("//pcweb-assets.mercdn.net/assets/img/card/discover.svg?2226206775", size: "49x15")
      =button_to "削除する", card_path, method: :delete
    - else 
      = link_to '登録してください', new_card_path, class: 'card_resistration'

app/views/cards/new.html.haml
.card-wrapper
  %h2.card-title クレジットカード情報入力
  =form_tag(cards_path, method: :post, id: 'charge-form', name: 'chargeForm') do
    %span.payment-errors
    .card-number
      %label カード番号
      %span.required-mark 必須
      %input.number{maxlength: "16", name:"number", placeholder: "半角数字のみ", type: "text"}/
      %ul
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/visa.svg?2226206775', alt: '', height: '20', width: '40', class: ''
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/master-card.svg?2226206775', alt: '', height: '20', width: '40', class: ''
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/jcb.svg?2226206775', alt: '', height: '20', width: '40', class: ''
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/american_express.svg?2226206775', alt: '', height: '20', width: '40', class: ''
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?2226206775', alt: '', height: '20', width: '40', class: ''
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/discover.svg?2226206775', alt: '', height: '20', width: '40', class: ''
    .card-cvc
      %label セキュリティコード
      %span.required-mark 必須
      %input.cvc{ maxlength:"3", name: "cvc", placeholder: "CVC", type: "text"}/
    .card-expiration
      %label 有効期限
      %span.required-mark 必須
      .exp_form
        = select_tag(:exp_month, options_for_select(Card::MONTHS))
        %span 月
        = select_tag(:exp_year, options_for_select(Card::YEARS))
        %span 年
    %button.submit-btn{ type: "submit"} 追加する